# Generated by Django 5.2.6 on 2025-09-13 14:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CVProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('address', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('date_awarded', models.DateField(blank=True, null=True)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='internship_and_job.cvprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField(blank=True, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='internship_and_job.cvprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='internship_and_job.cvprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('post_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('intern', 'Internship')], max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('education_requirements', models.CharField(blank=True, max_length=255, null=True)),
                ('previous_experience', models.CharField(blank=True, max_length=255, null=True)),
                ('skills_needed', models.TextField(blank=True, null=True)),
                ('other_requirements', models.TextField(blank=True, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('entry_level', 'Entry-Level'), ('mid_level', 'Mid-Level'), ('senior_level', 'Senior-Level'), ('all_levels', 'All Experience Levels')], max_length=20, null=True)),
                ('work_environment', models.CharField(blank=True, choices=[('in_office', 'In-Office'), ('hybrid', 'Hybrid'), ('remote', 'Fully Remote')], max_length=20, null=True)),
                ('industry', models.CharField(blank=True, choices=[('it', 'Information Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('others', 'Others (Specify)')], max_length=20, null=True)),
                ('industry_specification', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_and_job.cvprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship_and_job.job')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('proficiency', models.CharField(blank=True, max_length=255, null=True)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='internship_and_job.cvprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('cv_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='internship_and_job.cvprofile')),
            ],
        ),
    ]
