# Generated by Django 5.0.6 on 2024-09-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_and_job', '0006_cvprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education_requirements',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='other_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='previous_experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='skills_needed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
