# Generated by Django 5.0.6 on 2024-09-27 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_and_job', '0007_job_education_requirements_job_other_requirements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
