# Generated by Django 5.0.6 on 2024-09-27 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship_and_job', '0008_job_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='proficiency',
        ),
    ]
