# Generated by Django 5.0.6 on 2024-09-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_and_job', '0009_remove_language_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='proficiency',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
