# Generated by Django 5.0.6 on 2024-09-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship_and_job', '0010_language_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='proficiency',
        ),
    ]
