# Generated by Django 5.0.6 on 2024-09-27 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship_and_job', '0011_remove_language_proficiency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='description',
        ),
    ]
