# Generated by Django 5.0.6 on 2024-09-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship_and_job', '0012_remove_award_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
    ]
