# Generated by Django 5.0.6 on 2024-09-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_and_job', '0013_remove_education_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='date_awarded',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='proficiency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
