# Generated by Django 5.0.6 on 2024-09-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship_and_job', '0014_award_date_awarded_award_position_education_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvprofile',
            name='address',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
