# Generated by Django 5.0.6 on 2024-10-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0004_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='post_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
