# Generated by Django 5.0.6 on 2024-10-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_and_found', '0005_item_post_date_alter_item_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='post_date',
        ),
        migrations.AlterField(
            model_name='item',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
