# Generated by Django 5.0.6 on 2024-10-03 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_reply_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='parent',
            new_name='parent_reply',
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment'),
        ),
    ]
