# Generated by Django 5.0.6 on 2024-10-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_likedislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='reaction',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=7),
        ),
    ]
