# Generated by Django 5.2.6 on 2025-09-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image_360', models.ImageField(upload_to='360_images/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
