# Generated by Django 5.2.6 on 2025-10-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
