# Generated by Django 5.2.6 on 2025-10-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_scheduler', '0002_facultyprofile_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='facultyavailability',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
