# Generated by Django 5.0.6 on 2024-10-06 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_group_app', '0002_alter_notificationstudy_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstudy',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='study_group_app.group'),
            preserve_default=False,
        ),
    ]
