# Generated by Django 5.2.6 on 2025-09-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livelocation',
            name='display_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
