# Generated by Django 5.2.6 on 2025-09-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle_tracker', '0002_livelocation_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='end_latitude',
            field=models.FloatField(default=23.810331),
        ),
        migrations.AddField(
            model_name='route',
            name='end_longitude',
            field=models.FloatField(default=90.412521),
        ),
        migrations.AddField(
            model_name='route',
            name='start_latitude',
            field=models.FloatField(default=23.7808875),
        ),
        migrations.AddField(
            model_name='route',
            name='start_longitude',
            field=models.FloatField(default=90.2792371),
        ),
    ]
