# Generated by Django 5.2.6 on 2025-09-26 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle_tracker', '0003_route_end_latitude_route_end_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='end_latitude',
        ),
        migrations.RemoveField(
            model_name='route',
            name='end_longitude',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_latitude',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_longitude',
        ),
    ]
