# Generated by Django 5.2.6 on 2025-09-13 14:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(default='Unknown Degree', max_length=255)),
                ('trimester', models.CharField(default='Unknown Trimester', max_length=255)),
                ('course_title', models.CharField(max_length=255)),
                ('course_code', models.CharField(max_length=255)),
                ('material_type', models.CharField(max_length=255)),
                ('material_description', models.TextField(blank=True)),
                ('admin_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='materials/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='course_materials_and_feedback.coursematerial')),
            ],
        ),
    ]
