# Generated by Django 5.2.6 on 2025-09-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_materials_and_feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedepartment',
            name='trimester',
            field=models.CharField(default='trimester', max_length=255),
        ),
    ]
