# Generated by Django 5.2.6 on 2025-09-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_materials_and_feedback', '0002_coursedepartment_trimester'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
